# Generated by Django 3.2.8 on 2021-11-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_id',
            field=models.IntegerField(choices=[(1, '8:00'), (2, '8:30'), (3, '9:00'), (4, '9:30'), (5, '10:00'), (6, '10:30'), (7, '11:00'), (8, '11:30'), (9, '12:00'), (10, '12:30'), (11, '13:00'), (12, '13:30'), (13, '14:00'), (14, '14:30'), (15, '15:00'), (16, '15:30'), (17, '16:00'), (18, '16:30'), (19, '17:00'), (20, '17:30'), (21, '18:00'), (22, '18:30'), (23, '19:00'), (24, '19:30'), (25, '20:00')]),
        ),
    ]
